language: php

php:
  - 5.6

env:
    - DB_CONNECTION=testing APP_ENV=testing CACHE_DRIVER=array SESSION_DRIVER=array QUEUE_DRIVER=sync MAIL_DRIVER=log

sudo: false

install:
    - composer install --no-interaction --prefer-source
    - php artisan migrate

script: vendor/bin/phpunit