language: php

php:
  - 5.6

env:
    global:
        - DB_CONNECTION=testing

sudo: false

install:
    - composer install --no-interaction --prefer-source
    - php artisan migrate --env="testing"
    - chmod -R o+w storage/
    - chmod -R o+w public/images/

script: vendor/bin/phpunit