language: php

php:
  - 7.0

env:
  - TRAVIS_NODE_VERSION="6"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - node_modules

before_install:
  # INSTALL MYSQL 5.6
  # (https://github.com/piwik/piwik/commit/20bd2e1c24e5d673dce3feb256204ad48c29f160)
  # TODO: Remove when mysql 5.6 is provided by travis.
  # Otherwise, our migrations will raise a syntax error.
  - "sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
  - "sudo apt-get autoremove"
  - "sudo apt-get install libaio1"
  - "wget -O mysql-5.6.14.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.14-debian6.0-x86_64.deb/from/http://cdn.mysql.com/"
  - "sudo dpkg -i mysql-5.6.14.deb"
  - "sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server"
  - "sudo ln -s /opt/mysql/server-5.6/bin/* /usr/bin/"
  - "sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf"
  - "sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf"
  - "sudo sed -i'' 's/basedir[^=]\\+=.*$/basedir = \\/opt\\/mysql\\/server-5.6/' /etc/mysql/my.cnf"
  - "sudo /etc/init.d/mysql.server start"
  - mysql --version
  - mysql -e "SELECT VERSION();"
  # /END MYSQL 5.6
  - travis_retry gem update --system
  - travis_retry gem install bundler

sudo: false

install:
    - composer install --prefer-dist
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - npm install --no-optional
    - cp .env.travis .env
    - chmod -R o+w storage/
    - mysql -e 'create database trip2;'
    - php artisan migrate:refresh
    - gulp
    - gulp v1

script:
    - ./vendor/bin/phpunit

notifications:
    email: false
    slack: tripikad:Rb20AN0r1arWwhxIBl9DNaZ5