language: php

node_js:
  - "6"

php:
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: false

install:
    - composer update --prefer-dist
    - npm install
    - cp .env.travis .env
    - chmod -R o+w storage/
    - mysql -e 'create database IF NOT EXISTS trip2;'

before_script:
    - php artisan migrate:refresh

script:
    - phpunit
    - npm run test

notifications:
    email: false
    slack: tripikad:Rb20AN0r1arWwhxIBl9DNaZ5