language: php

php:
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: false

install:
    - echo 'function composer() { COMPOSER="$(which composer)" || { echo "Could not find composer in path" >&2 ; return 1 ; } && sudo php5dismod -s cli xdebug ; $COMPOSER "$@" ; STATUS=$? ; sudo php5enmod -s cli xdebug ; return $STATUS ; }' >> ~/.bash_aliases
    - . ~/.bash_aliases
    - composer update --prefer-dist
    - cp .env.travis .env
    - chmod -R o+w storage/
    - mysql -e 'create database IF NOT EXISTS trip2;'

before_script:
    - php artisan migrate:refresh

script: phpunit

notifications:
    email: false
    slack: tripikad:Rb20AN0r1arWwhxIBl9DNaZ5