name: Prettier

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run npm install
        run: npm ci
      - name: Run prettier
        run: npm run prettier
      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply prettier changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
